// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.KeyPhrase", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Name");

                    b.ToTable("KeyPhrases");
                });

            modelBuilder.Entity("Domain.Entities.Website", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Url");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("Domain.Entities.WebsiteKeyPhrase", b =>
                {
                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("KeyPhraseName")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("WebsiteUrl", "KeyPhraseName");

                    b.HasIndex("KeyPhraseName");

                    b.ToTable("WebsiteKeyPhrases");
                });

            modelBuilder.Entity("Domain.Entities.WebsiteKeyPhrase", b =>
                {
                    b.HasOne("Domain.Entities.KeyPhrase", "KeyPhrase")
                        .WithMany("WebsitesKeyPhrases")
                        .HasForeignKey("KeyPhraseName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Website", "Website")
                        .WithMany("WebsiteKeyPhrases")
                        .HasForeignKey("WebsiteUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyPhrase");

                    b.Navigation("Website");
                });

            modelBuilder.Entity("Domain.Entities.KeyPhrase", b =>
                {
                    b.Navigation("WebsitesKeyPhrases");
                });

            modelBuilder.Entity("Domain.Entities.Website", b =>
                {
                    b.Navigation("WebsiteKeyPhrases");
                });
#pragma warning restore 612, 618
        }
    }
}
